[ua]
  languageName = "Українська"
  contentDir = "content/ua"
  weight = 10
  [ua.params]
    languageISO = "UK"
    languageTag = "uk-UA"
#    titleAddition = "Modern documentatie-thema"
#    description = "Doks is een Hugo-thema waarmee je moderne documentatie-websites kunt bouwen die veilig, snel en klaar voor SEO zijn — standaard."
#    titleHome = "Doks thema"
    footer = "Працює на <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a> та <a href=\"https://getdoks.org/\">Doks</a>"
    alertText = "🚧 Сайт знаходиться у стадії розробки. Контент може бути неповним або невірним."

[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 15
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
