[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.15.0"
  NPM_VERSION = "9.5.0"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENV = "next"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
    baseUrl = "https://mvano.com/"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "bing",
      "yandex"
    ]


#[[headers]]
#  for = "/*"
#  [headers.values]
#    Content-Security-Policy = "script-src-elem 'self' 'unsafe-inline' https://app.pryvy.io"

#    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; font-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com"


[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self'; frame-ancestors https://jamstackthemes.dev; manifest-src 'self' https://*.netlify.app; connect-src 'self' https://*.netlify.app; font-src 'self' https://*.netlify.app; img-src 'self' https://*.netlify.app data: https://i.giphy.com; script-src 'self' https://*.netlify.app https://app.pryvy.io; style-src 'self' https://*.netlify.app 'unsafe-inline'"


[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
  